FORMAT: 1A

# ipfs

The API for interacting with IPFS nodes.

## Add [/add{?stream%2Dchannels}]

### Add a Single File [POST]
Add a file to IPFS returning the hash and name. The name
value will only be set if you are actually sending a file.

+ Parameters
    + stream%2Dchannels (optional, boolean) - Should the result be returned in a streaming manner.

+ Request (multipart/form-data; boundary=---BOUNDARY)

        -----BOUNDARY
        Content-Disposition: form-data; name="image[file]"; filename="file.txt"
        Content-Type: text/plain
    
        hello world
        -----BOUNDARY

+ Response 201 (application/json)

  + Headers

            X-Chunked-Output: 1

  + Body

            {
                "Name": "file.txt",
                "Hash": "myhash"
            }

## bitswap [/bitswap]
A set of commands to manipulate the bitswap agent

### bitswap stat [/stat]
Show some diagnostic information on the bitswap agent

+ Request (text/plain)

+ Response 201 (application/json)

    + Body
    
            {
              "ProvideBufLen": 0,
              "Wantlist": null,
              "Peers": [
                "QmNjRVohhWBX31EoaAXkrj5mPF9vQNcTVvQgWHNwdxweCN",
                "QmSoLV4Bbm51jM9C4gDYZQ9Cy3U6aXMJDAbzgu2fzaDs64",
                "QmSoLer265NRgSp2LA3dPaeykiS1J6DifTC88f5uVQKNAd",
                "QmSoLju6m7xTh3DuokvT3886QRYqxAzb1kShaanJgW36yx",
                "QmSoLnSGccFuZQJzRadHn95W2CrSFmZuTdDWP8HXaHca9z",
                "QmSoLueR4xBeUbY9WZ9xGUUxunbKWcrNFTDAadQJmocnWm",
                "QmfTbyfUhkY9PkthZ7DNBVRHPjva3vR6wLhsj7jMRUymre"
              ],
              "BlocksReceived": 0,
              "DupBlksReceived": 0,
              "DupDataReceived": 0
            }







